// 全国事业编招聘数据 - 自动生成
// 更新时间: 2026-06-07T07:54:45+08:00
window.zhaopinData = {
  "metadata": {
    "version": "1.0",
    "lastUpdated": "2026-06-07T07:54:45+08:00",
    "source": "shiyebian.com / offcn.com / 各省市人社局 / 手动录入",
    "totalEntries": 28,
    "precision": "★★★",
    "autoGenerated": true,
    "note": "自动爬取 + 手动校正。截止日期为估算, 请以官方公告为准。"
  },
  "examCategories": [
    "A",
    "B",
    "C",
    "D",
    "E"
  ],
  "examCategoryNames": {
    "A": "综合管理",
    "B": "社会科学",
    "C": "自然科学",
    "D": "中小学教师",
    "E": "医疗卫生"
  },
  "natureLabels": {
    "est": "事业编",
    "hire": "聘用制",
    "aux": "辅警/非编",
    "ent": "企业岗"
  },
  "positionTemplates": [
    {
      "name": "综合管理岗",
      "education": "本科",
      "major": "管理",
      "fresh": "否",
      "hireCount": 2
    },
    {
      "name": "信息化管理岗",
      "education": "本科",
      "major": "计算机",
      "fresh": "是",
      "hireCount": 3
    },
    {
      "name": "财务管理岗",
      "education": "本科",
      "major": "财会",
      "fresh": "否",
      "hireCount": 2
    },
    {
      "name": "医疗卫生岗",
      "education": "本科",
      "major": "医学",
      "fresh": "否",
      "hireCount": 4
    },
    {
      "name": "教学管理岗",
      "education": "硕士",
      "major": "教育",
      "fresh": "否",
      "hireCount": 2
    }
  ],
  "entries": [
    {
      "name": "2025年绵阳平武县人力资源和社会保障局四川省属公费师范毕业生直接考核招聘公告（14人",
      "province": "四川",
      "city": "绵阳",
      "hireCount": 14,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年度鄂州市法院系统招聘雇员制审判辅助人员公告（4人）",
      "province": "湖北",
      "city": "鄂州",
      "hireCount": 4,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年度鄂州市检察机关招聘雇员制检察辅助人员公告（5人）",
      "province": "湖北",
      "city": "鄂州",
      "hireCount": 5,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年晋城市城市体验中心（筹备）招聘工作人员公告（10人）",
      "province": "山西",
      "city": "晋城",
      "hireCount": 10,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年广西财经学院招聘教职人员（第二批）公告 （12人）",
      "province": "广西",
      "city": "南宁",
      "hireCount": 12,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年中国科学院山西煤炭化学研究所编制外人员招聘启事（1人）",
      "province": "山西",
      "city": "太原",
      "hireCount": 1,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年晋中市昔阳县招聘优秀村党组织书记进乡镇事业单位公告（1人）",
      "province": "山西",
      "city": "晋中",
      "hireCount": 1,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年山东胜利职业学院招聘工作人员简章（45人）",
      "province": "山东",
      "city": "济南",
      "hireCount": 45,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年上海市民政第一精神卫生中心招聘工作人员公告（7人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 7,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "E",
      "nature": "est"
    },
    {
      "name": "2025年淄博市高青县司法局招聘专职人民调解员公告（2人）",
      "province": "青海",
      "city": "西宁",
      "hireCount": 2,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年上海评弹艺术传习所（上海评弹团）招聘工作人员公告（2人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 2,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年上海对外经贸大学辅导员（第二批）招聘公告（7人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 7,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年上海市第二轻工业学校招聘工作人员公告（2025第二批）（2人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 2,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年上海市文化和旅游事业发展中心招聘工作人员公告（2人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 2,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "B",
      "nature": "est"
    },
    {
      "name": "2025年度上海交通大学医学院附属新华医院管理岗位招聘公告（11人）",
      "province": "上海",
      "city": "浦东新区",
      "hireCount": 11,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年北京中医药大学东方医院枣庄医院招聘合同制工作人员公告（100人）",
      "province": "北京",
      "city": "东城区",
      "hireCount": 100,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "hire"
    },
    {
      "name": "2025年北京农学院第二批招聘工作人员公告",
      "province": "北京",
      "city": "东城区",
      "hireCount": 1,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年德州市夏津县人民医院招聘备案制工作人员简章（20人）",
      "province": "天津",
      "city": "和平区",
      "hireCount": 20,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "E",
      "nature": "est"
    },
    {
      "name": "2025年重庆市长寿区教育事业单位面向应届毕业农村小学全科教师考核招聘工作人员公告（",
      "province": "重庆",
      "city": "长寿区",
      "hireCount": 1,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "D",
      "nature": "est"
    },
    {
      "name": "2025年南京市玄武湖周边地区综合管理办公室下属事业单位编外人员招聘公告（2人）",
      "province": "北京",
      "city": "东城区",
      "hireCount": 2,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "A",
      "nature": "est"
    },
    {
      "name": "2025年韶关市仁化县医共体“青年人才”暨医疗卫生专业技术人员招聘公告（21人）",
      "province": "青海",
      "city": "西宁",
      "hireCount": 21,
      "announceDate": "2026-06-07",
      "deadline": "2026-06-21",
      "examCategory": "E",
      "nature": "est"
    },
    {
      "name": "西藏昌都市市直事业单位公开遴选招聘公告",
      "province": "西藏",
      "city": "昌都市",
      "posCount": 10,
      "hireCount": 10,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "A",
      "nature": "est",
      "announceDate": "2026-05-22",
      "deadline": "2026-05-29",
      "url": "http://hrss.xizang.gov.cn/"
    },
    {
      "name": "福建龙岩市高校毕业生服务社区计划招募公告",
      "province": "福建",
      "city": "龙岩市",
      "posCount": 20,
      "hireCount": 20,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "A",
      "nature": "est",
      "announceDate": "2026-05-20",
      "deadline": "2026-06-10",
      "url": "http://rst.fujian.gov.cn/"
    },
    {
      "name": "2025年江苏无锡锡山区部分事业单位招聘公告",
      "province": "江苏",
      "city": "无锡市",
      "posCount": 8,
      "hireCount": 8,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "A",
      "nature": "est",
      "announceDate": "2026-05-18",
      "deadline": "2026-06-11",
      "url": "http://hrss.wuxi.gov.cn/"
    },
    {
      "name": "重庆师范大学2025年事业单位公开招聘公告",
      "province": "重庆",
      "city": "重庆市",
      "posCount": 30,
      "hireCount": 30,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "D",
      "nature": "est",
      "announceDate": "2026-05-16",
      "deadline": "2026-06-08",
      "url": "https://www.cqnu.edu.cn/"
    },
    {
      "name": "2025年日照市岚山区部分事业单位公开招聘工作人员公告",
      "province": "山东",
      "city": "日照市",
      "posCount": 15,
      "hireCount": 15,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "A",
      "nature": "est",
      "announceDate": "2026-05-15",
      "deadline": "2026-06-11",
      "url": "https://hrss.rizhao.gov.cn/"
    },
    {
      "name": "中国农业科学院2025年度第二批招聘公告",
      "province": "北京",
      "city": "",
      "posCount": 12,
      "hireCount": 12,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "C",
      "nature": "est",
      "announceDate": "2026-05-12",
      "deadline": "2026-06-05",
      "url": "http://www.caas.cn/"
    },
    {
      "name": "中国文学艺术界联合会所属事业单位2025年公开招聘公告",
      "province": "北京",
      "city": "",
      "posCount": 5,
      "hireCount": 5,
      "applicantCount": 0,
      "auditedCount": 0,
      "ratio": 0,
      "examCategory": "B",
      "nature": "est",
      "announceDate": "2026-05-10",
      "deadline": "2026-06-14",
      "url": "https://www.mohrss.gov.cn/"
    }
  ]
};
